service: API de consultas médicas

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  getAgendas:
    handler: src/agenda/controller/agenda.handler
    events:
      - http:
          path: /agenda
          method: get
  createAppointment:
    handler: src/agendamento/controller/agendamento.handler
    events:
      - http:
          path: /agendamento
          method: post